version: '2'
# Define the services/containers to be run
services:
  myapp: #name of node service
    container_name: myapp
    restart: always #restart container after failure
    build: ./ # directory of the Dockerfile
    ports:
      - "3000:3000" #ports forwarding
    links:
      - database # link to the database service
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database: # name of database service
    container_name: mongo
    image: mongo # image from Dockerhub
    ports:
      - "27017:27017"